; Preset MGD Edge — Super Mario Odyssey no A15 (Mali barata)
; Aplicar por cima dos defaults do Eden. Medir cada bloco.

[renderer]
api = vulkan
resolution_factor = 0.5
vsync = off
aa = off
shadows = off
post_processing = off
gpu_accuracy = normal
async_shaders = on
docked_mode = off

[cpu]
fast_cpu = on
multicore = on
accuracy = unsafe
fastmem = on

[mgd_edge]
; agressivo experimental (modo Edge)
resolution_factor = 0.4
gpu_accuracy = low
frame_reuse_static = on
lod_aggressive = on
batch_draws = on

[system]
close_background = true
battery_saver = off
animations = 0.5x
cooled_device = true
